/** Kod bloklarının üst çubuğunda görünen dil adları. */
const LANGUAGE_LABELS: Readonly<Record<string, string>> = {
  plaintext: 'Kod',
  plain: 'Kod',
  text: 'Metin',
  txt: 'Metin',
  java: 'Java',
  kotlin: 'Kotlin',
  kt: 'Kotlin',
  groovy: 'Groovy',
  gradle: 'Gradle',
  scala: 'Scala',
  js: 'JavaScript',
  javascript: 'JavaScript',
  mjs: 'JavaScript',
  cjs: 'JavaScript',
  jsx: 'JSX',
  ts: 'TypeScript',
  typescript: 'TypeScript',
  tsx: 'TSX',
  json: 'JSON',
  jsonc: 'JSON',
  json5: 'JSON5',
  yaml: 'YAML',
  yml: 'YAML',
  toml: 'TOML',
  xml: 'XML',
  html: 'HTML',
  css: 'CSS',
  scss: 'SCSS',
  sass: 'Sass',
  sql: 'SQL',
  bash: 'Terminal',
  sh: 'Terminal',
  shell: 'Terminal',
  shellscript: 'Terminal',
  zsh: 'Terminal',
  console: 'Terminal',
  powershell: 'PowerShell',
  ps1: 'PowerShell',
  bat: 'Batch',
  cmd: 'Batch',
  dockerfile: 'Dockerfile',
  docker: 'Dockerfile',
  properties: 'Properties',
  ini: 'INI',
  dotenv: '.env',
  python: 'Python',
  py: 'Python',
  go: 'Go',
  rust: 'Rust',
  rs: 'Rust',
  c: 'C',
  cpp: 'C++',
  'c++': 'C++',
  csharp: 'C#',
  cs: 'C#',
  php: 'PHP',
  ruby: 'Ruby',
  rb: 'Ruby',
  swift: 'Swift',
  dart: 'Dart',
  r: 'R',
  md: 'Markdown',
  markdown: 'Markdown',
  diff: 'Diff',
  http: 'HTTP',
  graphql: 'GraphQL',
  gql: 'GraphQL',
  nginx: 'Nginx',
  makefile: 'Makefile',
  make: 'Makefile',
  mermaid: 'Mermaid',
};

export function languageLabel(language: string | undefined): string {
  const key = (language ?? '').trim().toLowerCase();
  if (!key) return 'Kod';
  return LANGUAGE_LABELS[key] ?? key.charAt(0).toUpperCase() + key.slice(1);
}
